name: "Lokalise Branch Actions"
description: "Lokalise branch actions"
inputs:
  projectId:
    description: "Lokalise project id"
    required: true

  apiKey:
    description: "Lokalise key with write permission"
    required: true

  branchName:
    description: "Lokalise branch name"
    required: false

  actionType:
    description: 'branch action type ["findByName", "create", "merge", "createAndBackport"]'
    required: true

  actionPayload:
    description: 'payload of branch action'
    required: true

outputs:
  findByNameResult:
    description: "Result of findByName action"
  createResult:
    description: "Result of create action"
  mergeResult:
    description: "Result of merge action"

runs:
  using: "node12"
  main: "index.js"
