name: "Lokalise Branch Actions"
description: "Lokalise branch actions"
inputs:
  projectId:
    description: "Lokalise project id"
    required: true

  apiKey:
    description: "Lokalise key with write permission"
    required: true

  actionType:
    description: 'branch action type ["findByName", "create", "merge", "createAndBackport"]'
    required: true

  actionPayload:
    description: 'payload of branch action'
    required: true

outputs:
  projectName:
    description: "Lokalise project name"
  error:
    description: "Error data when action failed"
  result:
    description: "Result of action"

runs:
  using: "node16"
  main: "dist/index.js"
